#spring:
#  datasource:
#    url: jdbc:h2:./devdb
#    username: sa
#    password: 
#  jpa:
#    hibernate:
#      ddl-auto: update  

spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none